import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import UserContextProvider from "@/components/hook/userHook";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GoStock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <UserContextProvider>
          <div className="flex flex-col h-screen ">
          <Header />
           <div className="mt-[78px]">{children}</div>
          <Footer />
          </div>
         
        </UserContextProvider>
      </body>
    </html>
  );
}
